"database0":
  "config": "mongodb://localhost:27017/"
  "db": "minos"
  
"database":
  "config": "localhost"
  "db": "pain"
  "user": "root"
  "password": "123456"

"session":
  "db": !!int "1"
  "host": "localhost"
  "port": !!int "6379"